"""Build DataSynth v73 candidate with Phase 1 rule-truth sidecars.

This patch does not regenerate journal data. It creates a candidate dataset that
reuses the current production DataSynth files and adds rule-condition truth files
separate from injected/anomaly labels.
"""

from __future__ import annotations

import json
import os
import shutil
from pathlib import Path
from typing import Iterable

import pandas as pd


ROOT = Path(__file__).resolve().parents[2]
SRC = Path(os.environ.get("DATASYNTH_RULE_TRUTH_SOURCE", ROOT / "data" / "journal" / "primary" / "datasynth_v72_candidate"))
if not SRC.exists():
    SRC = ROOT / "data" / "journal" / "primary" / "datasynth"
DEST = Path(os.environ.get("DATASYNTH_RULE_TRUTH_DEST", ROOT / "data" / "journal" / "primary" / "datasynth_v73_candidate"))
LABELS = DEST / "labels"
YEARS = (2022, 2023, 2024)
REQUIRED_FIELDS = [
    "document_id",
    "company_code",
    "fiscal_year",
    "fiscal_period",
    "posting_date",
    "document_date",
    "document_type",
    "gl_account",
    "debit_amount",
    "credit_amount",
]
APPROVAL_NEAR_RATIO = 0.90
APPROVAL_LIMITS = (10_000_000, 100_000_000, 1_000_000_000, 5_000_000_000, 10_000_000_000, 50_000_000_000)


def _safe_link_or_copy(src: Path, dest: Path) -> None:
    if dest.exists():
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    try:
        os.link(src, dest)
    except OSError:
        shutil.copy2(src, dest)


def _materialize_candidate() -> None:
    if not SRC.exists():
        raise SystemExit(f"missing source dataset: {SRC}")
    if DEST.exists():
        # This directory is generated by this script. Rebuild it so the v73 baseline
        # cannot accidentally mix production files with the v72 patch chain.
        shutil.rmtree(DEST)
    DEST.mkdir(parents=True, exist_ok=True)
    for path in SRC.rglob("*"):
        rel = path.relative_to(SRC)
        target = DEST / rel
        if path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
        else:
            _safe_link_or_copy(path, target)
    LABELS.mkdir(parents=True, exist_ok=True)


def _read_years(usecols: list[str]) -> pd.DataFrame:
    frames: list[pd.DataFrame] = []
    for year in YEARS:
        path = DEST / f"journal_entries_{year}.csv"
        available = pd.read_csv(path, nrows=0).columns.tolist()
        cols = [col for col in usecols if col in available]
        frame = pd.read_csv(path, dtype=str, usecols=cols, low_memory=False)
        for col in usecols:
            if col not in frame.columns:
                frame[col] = pd.NA
        frames.append(frame[usecols])
    return pd.concat(frames, ignore_index=True)


def _doc_base(rows: pd.DataFrame) -> pd.DataFrame:
    for col in ("debit_amount", "credit_amount"):
        rows[col] = pd.to_numeric(rows[col], errors="coerce").fillna(0.0)
    docs = rows.groupby("document_id", as_index=False).agg(
        fiscal_year=("fiscal_year", "first"),
        company_code=("company_code", "first"),
        document_number=("document_number", "first"),
        document_type=("document_type", "first"),
        posting_date=("posting_date", "first"),
        document_date=("document_date", "first"),
        fiscal_period=("fiscal_period", "first"),
        business_process=("business_process", "first"),
        source=("source", "first"),
        created_by=("created_by", "first"),
        approved_by=("approved_by", "first"),
        approval_date=("approval_date", "first"),
        debit_total=("debit_amount", "sum"),
        credit_total=("credit_amount", "sum"),
        line_count=("document_id", "size"),
    )
    docs["document_amount"] = docs[["debit_total", "credit_total"]].max(axis=1)
    return docs


def _load_doc_context() -> pd.DataFrame:
    rows = _read_years([
        "document_id",
        "fiscal_year",
        "company_code",
        "document_number",
        "document_type",
        "posting_date",
        "document_date",
        "fiscal_period",
        "business_process",
        "source",
        "created_by",
        "approved_by",
        "approval_date",
        "debit_amount",
        "credit_amount",
        "gl_account",
        "sod_violation",
        "sod_conflict_type",
    ])
    return _doc_base(rows)


def _load_rows_for_field_rules() -> pd.DataFrame:
    return _read_years(REQUIRED_FIELDS + [
        "document_number",
        "business_process",
        "source",
        "created_by",
        "approved_by",
        "approval_date",
        "sod_violation",
        "sod_conflict_type",
    ])


def _load_coa_accounts() -> set[str]:
    data = json.loads((DEST / "chart_of_accounts.json").read_text(encoding="utf-8"))
    return {str(row.get("account_number", "")).strip() for row in data.get("accounts", []) if str(row.get("account_number", "")).strip()}


def _load_approval_limits() -> dict[str, float]:
    path = DEST / "master_data" / "employees.json"
    employees = json.loads(path.read_text(encoding="utf-8"))
    return {
        str(row.get("user_id", "")).strip(): float(row.get("approval_limit") or 0.0)
        for row in employees
        if str(row.get("user_id", "")).strip()
    }


def _base_truth(docs: pd.DataFrame, rule_id: str, basis: str) -> pd.DataFrame:
    keep = [
        "document_id",
        "fiscal_year",
        "company_code",
        "document_number",
        "document_type",
        "posting_date",
        "business_process",
        "source",
    ]
    out = docs[[col for col in keep if col in docs.columns]].copy()
    out["rule_id"] = rule_id
    out["expected_hit"] = True
    out["truth_layer"] = "rule_truth"
    out["truth_basis"] = basis
    out["evaluation_unit"] = "document"
    return out


def _write_json_records(path: Path, df: pd.DataFrame) -> None:
    records = df.where(pd.notna(df), None).to_dict(orient="records")
    path.write_text(json.dumps(records, ensure_ascii=False, indent=2), encoding="utf-8")


def _write_truth(rule_id: str, df: pd.DataFrame) -> pd.DataFrame:
    stem = f"rule_truth_{rule_id.replace('-', '_')}"
    path = LABELS / f"{stem}.csv"
    df.to_csv(path, index=False)
    _write_json_records(LABELS / f"{stem}.json", df)
    if "fiscal_year" in df.columns:
        for year in YEARS:
            subset = df.loc[df["fiscal_year"].astype(str).eq(str(year))]
            subset.to_csv(LABELS / f"{stem}_{year}.csv", index=False)
            _write_json_records(LABELS / f"{stem}_{year}.json", subset)
    return df


def _truth_from_sidecar(rule_id: str, filename: str, basis: str, unit: str = "document") -> pd.DataFrame:
    path = LABELS / filename
    if not path.exists():
        return pd.DataFrame(columns=["rule_id", "expected_hit", "truth_layer", "truth_basis", "evaluation_unit"])
    df = pd.read_csv(path, dtype=str, low_memory=False)
    if "expected_l202_label_document_id" in df.columns:
        df["document_id"] = df["expected_l202_label_document_id"]
    cols = [c for c in [
        "document_id",
        "fiscal_year",
        "company_code",
        "document_number",
        "document_type",
        "posting_date",
        "business_process",
        "source",
        "gl_account",
        "finding_id",
        "d02_group_key",
        "case_id",
    ] if c in df.columns]
    out = df[cols].drop_duplicates().copy()
    out["rule_id"] = rule_id
    out["expected_hit"] = True
    out["truth_layer"] = "rule_truth"
    out["truth_basis"] = basis
    out["evaluation_unit"] = unit
    return out


def _truth_from_labels(rule_id: str, labels: pd.DataFrame, anomaly_types: Iterable[str], docs: pd.DataFrame, basis: str) -> pd.DataFrame:
    wanted = set(anomaly_types)
    ids = set(labels.loc[labels["anomaly_type"].isin(wanted), "document_id"].dropna().astype(str))
    return _base_truth(docs.loc[docs["document_id"].astype(str).isin(ids)], rule_id, basis)


def build_truth() -> dict[str, int]:
    rows = _load_rows_for_field_rules()
    docs = _doc_base(rows)
    labels = pd.read_csv(LABELS / "anomaly_labels.csv", dtype=str, low_memory=False)
    outputs: list[pd.DataFrame] = []

    l101 = docs.loc[(docs["debit_total"] - docs["credit_total"]).abs().gt(1.0)].copy()
    outputs.append(_write_truth("L1-01", _base_truth(l101, "L1-01", "actual debit total and credit total are imbalanced")))

    missing_masks = []
    for col in REQUIRED_FIELDS:
        value = rows[col].astype("string").str.strip()
        missing_masks.append(value.isna() | value.eq("") | value.str.lower().isin({"nan", "none", "null", "<na>"}))
    missing_any = missing_masks[0]
    for mask in missing_masks[1:]:
        missing_any = missing_any | mask
    missing_docs = set(rows.loc[missing_any, "document_id"].dropna().astype(str))
    outputs.append(_write_truth("L1-02", _base_truth(docs.loc[docs["document_id"].astype(str).isin(missing_docs)], "L1-02", "required schema field is missing")))

    valid_accounts = _load_coa_accounts()
    acct = rows["gl_account"].astype("string").str.strip()
    invalid_docs = set(rows.loc[acct.notna() & acct.ne("") & ~acct.isin(valid_accounts), "document_id"].dropna().astype(str))
    outputs.append(_write_truth("L1-03", _base_truth(docs.loc[docs["document_id"].astype(str).isin(invalid_docs)], "L1-03", "journal account is not present in configured CoA")))

    limits = _load_approval_limits()
    docs["approval_limit"] = docs["approved_by"].astype("string").str.strip().map(limits)
    l104 = docs.loc[docs["approval_limit"].notna() & docs["document_amount"].gt(docs["approval_limit"])].copy()
    outputs.append(_write_truth("L1-04", _base_truth(l104, "L1-04", "document amount exceeds approved_by approval limit")))

    created = docs["created_by"].astype("string").str.strip()
    approved = docs["approved_by"].astype("string").str.strip()
    l105 = docs.loc[created.notna() & approved.notna() & created.ne("") & created.eq(approved)].copy()
    outputs.append(_write_truth("L1-05", _base_truth(l105, "L1-05", "created_by equals approved_by")))

    sod = rows["sod_violation"].astype("string").str.strip().str.lower().isin({"true", "1", "yes"})
    sod = sod | rows["sod_conflict_type"].astype("string").str.strip().fillna("").ne("")
    sod_docs = set(rows.loc[sod, "document_id"].dropna().astype(str))
    outputs.append(_write_truth("L1-06", _base_truth(docs.loc[docs["document_id"].astype(str).isin(sod_docs)], "L1-06", "SoD conflict signal is present in the transaction flow")))

    # L1-07 uses the current skipped-approval contract: no approver on a document that reaches an approval level.
    source = docs["source"].astype("string").str.strip().str.lower()
    no_approver = docs["approved_by"].astype("string").str.strip().fillna("").eq("")
    l107 = docs.loc[no_approver & ~source.isin({"automated", "batch", "interface", "system"}) & docs["document_amount"].ge(min(APPROVAL_LIMITS))].copy()
    outputs.append(_write_truth("L1-07", _base_truth(l107, "L1-07", "approval is skipped for a document requiring approval")))

    posting_month = pd.to_datetime(docs["posting_date"], errors="coerce").dt.month
    fiscal_period = pd.to_numeric(docs["fiscal_period"], errors="coerce")
    l108 = docs.loc[posting_month.notna() & fiscal_period.notna() & posting_month.ne(fiscal_period)].copy()
    outputs.append(_write_truth("L1-08", _base_truth(l108, "L1-08", "fiscal period does not match posting month")))

    missing_approval_date = docs["approval_date"].astype("string").str.strip().fillna("").eq("")
    l109 = docs.loc[missing_approval_date].copy()
    outputs.append(_write_truth("L1-09", _base_truth(l109, "L1-09", "approval_date is missing")))

    l201 = docs.loc[
        docs["approval_limit"].notna()
        & docs["approval_limit"].gt(0)
        & docs["document_amount"].ge(docs["approval_limit"] * APPROVAL_NEAR_RATIO)
        & docs["document_amount"].lt(docs["approval_limit"])
    ].copy()
    outputs.append(_write_truth("L2-01", _base_truth(l201, "L2-01", "document amount is just below approved_by approval limit")))

    sidecar_specs = [
        ("L2-02", "duplicate_payment_pairs.csv", "same payment appears to be paid again", "document_pair"),
        ("L3-03", "intercompany_population_truth.csv", "intercompany or related-party transaction population", "document"),
        ("L3-08", "missing_corrupted_description_truth.csv", "description is missing or corrupted", "document"),
        ("L3-09", "suspense_aging_review_population.csv", "suspense or clearing account remains unresolved beyond aging threshold", "document"),
        ("L3-10", "high_risk_account_review_population.csv", "configured high-risk account is used", "document"),
        ("L3-11", "cutoff_review_population.csv", "posting date and event date exceed cutoff tolerance", "document"),
        ("L4-02", "benford_finding_truth.csv", "group-level Benford distribution anomaly", "fiscal_year+company_code+gl_account"),
        ("L4-04", "rare_account_pair_review_population.csv", "rare debit-credit account pair review population", "document"),
        ("L4-05", "abnormal_hours_concentration_cases.csv", "user abnormal-hours concentration review condition", "document"),
        ("L4-06", "batch_review_population.csv", "batch source period-end, simultaneous, or amount-outlier review condition", "document"),
        ("D01", "account_activity_variance_review_population.csv", "company-account year-over-year activity variance review population", "fiscal_year+company_code+gl_account"),
        ("D02", "monthly_pattern_shift_review_population.csv", "company-account year-over-year monthly pattern shift review population", "fiscal_year+company_code+gl_account"),
    ]
    for rule_id, filename, basis, unit in sidecar_specs:
        outputs.append(_write_truth(rule_id, _truth_from_sidecar(rule_id, filename, basis, unit)))

    outputs.append(_write_truth("L2-03", _truth_from_labels("L2-03", labels, ["DuplicateEntry"], docs, "duplicate or near-duplicate entry label until detector-wide candidate truth is implemented")))
    outputs.append(_write_truth("L2-04", _truth_from_labels("L2-04", labels, ["ExpenseCapitalization", "ImproperCapitalization"], docs, "expense-to-asset capitalization candidate label until detector-wide candidate truth is implemented")))
    outputs.append(_write_truth("L2-05", _truth_from_labels("L2-05", labels, ["ReversedAmount", "ReversalEntry"], docs, "reversal or correction pattern label until detector-wide candidate truth is implemented")))
    outputs.append(_write_truth("L3-01", _truth_from_labels("L3-01", labels, ["MisclassifiedAccount"], docs, "valid CoA account used in process/account mismatch scenario")))

    manual_source = docs["source"].astype("string").str.strip().str.lower().isin({"manual", "adjustment"})
    outputs.append(_write_truth("L3-02", _base_truth(docs.loc[manual_source], "L3-02", "manual or adjustment source")))

    posting = pd.to_datetime(docs["posting_date"], errors="coerce")
    is_period_boundary = posting.dt.day.ge(26) | posting.dt.day.le(5)
    high_amount = docs["document_amount"].ge(docs["document_amount"].quantile(0.75))
    l304 = docs.loc[is_period_boundary.fillna(False) & (high_amount | manual_source)].copy()
    outputs.append(_write_truth("L3-04", _base_truth(l304, "L3-04", "period-end/start posting with high amount or manual source")))

    # Weekend/holiday sidecar exists for full contract; use it after computed L3-04.
    outputs.append(_write_truth("L3-05", _truth_from_sidecar("L3-05", "weekend_review_population.csv", "weekend or holiday posting", "document")))

    afterhours = _truth_from_sidecar("L3-06", "normal_after_hours_context.csv", "after-hours posting review population", "document")
    confirmed_afterhours = _truth_from_labels("L3-06", labels, ["AfterHoursPosting"], docs, "after-hours posting confirmed label")
    outputs.append(_write_truth("L3-06", pd.concat([afterhours, confirmed_afterhours], ignore_index=True).drop_duplicates()))

    doc_date = pd.to_datetime(docs["document_date"], errors="coerce")
    day_gap = (posting - doc_date).dt.days.abs()
    l307 = docs.loc[day_gap.gt(30).fillna(False)].copy()
    outputs.append(_write_truth("L3-07", _base_truth(l307, "L3-07", "posting date and document date differ beyond threshold")))

    l401 = _truth_from_sidecar("L4-01", "revenue_manipulation_l401_direct_truth.csv", "revenue account high-value z-score outlier", "document")
    outputs.append(_write_truth("L4-01", l401))
    l403 = _truth_from_sidecar("L4-03", "high_amount_review_population.csv", "high amount z-score and amount guard review population", "document")
    if l403.empty:
        l403 = _truth_from_labels("L4-03", labels, ["UnusuallyHighAmount", "StatisticalOutlier"], docs, "high amount outlier label fallback")
    outputs.append(_write_truth("L4-03", l403))

    combined = pd.concat(outputs, ignore_index=True, sort=False)
    combined.to_csv(LABELS / "rule_truth.csv", index=False)
    summary = {
        "candidate_version": "v73",
        "source_baseline": str(SRC.relative_to(ROOT)).replace("\\", "/"),
        "patch_scope": "add Phase 1 rule-condition truth sidecars without regenerating journal entries",
        "rule_truth_rows": int(len(combined)),
        "rule_counts": {str(k): int(v) for k, v in combined["rule_id"].value_counts().sort_index().to_dict().items()},
        "anti_fitting_note": "Rule truth is derived from source fields or broad review sidecars, not from detector scores. Audit issue truth remains separate.",
        "known_partial_rules": ["L2-03", "L2-04", "L2-05"],
    }
    (DEST / "V73_RULE_TRUTH_PATCH.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    (DEST / "FREEZE_V73_CANDIDATE.md").write_text(
        "# DataSynth v73 Candidate\n\n"
        f"Source baseline: `{str(SRC.relative_to(ROOT)).replace(chr(92), '/')}`.\n\n"
        "Scope: add Phase 1 rule-condition truth sidecars without regenerating journal entries.\n\n"
        "This candidate separates `rule_truth` from injected/audit issue labels.\n\n"
        f"```json\n{json.dumps(summary, ensure_ascii=False, indent=2)}\n```\n",
        encoding="utf-8",
    )
    return summary["rule_counts"]


def main() -> None:
    _materialize_candidate()
    counts = build_truth()
    print(json.dumps({"dataset": str(DEST), "rule_counts": counts}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
